dist: xenial
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
env:
  - FLASK_APP=todolist.py
install:
  - "pip install -r requirements.txt"
  - "pip install -r test-requirements.txt"
script: "flask test"
