language: python
python:
  - "2.7"
  - "3.5"
env:
  - FLASK_APP=todolist.py
  - SECRET_KEY='keep no secrets form travis'
install:
  - "pip install -r requirements.txt"
  - "pip install -r test-requirements.txt"
script: "flask test"
